export interface Person {
    name: string,
    height: number,
    mass: number,
    hair_color: string,
    skin_color: string,
    eye_color: string,
    birth_year: string,
    gender: string,
    homeworld: string,
    films: string[],
    species: string[],
    vehicles: string[],
    starships: string[],
    created: string,
    edited: string,
    url: string,
}

export interface Planet {
    name: string,
    rotation_period: number,
    orbital_period: number,
    diameter: number,
    climate: string,
    gravity: string,
    terrain: string,
    surface_water: number,
    population: number,
    residents: string[],
    films: string[],
    created: string,
    edited: string,
    url: string,
}

export interface Starship {
    name: string,
    model: string,
    manufacturer: string,
    cost_in_credits: number,
    length: number,
    max_atmosphering_speed: string,
    crew: number,
    passengers: number,
    cargo_capacity: number,
    consumables: string,
    hyperdrive_rating: number,
    MGLT: number,
    starship_class: string,
    pilots: string[],
    films: string[],
    created: string,
    edited: string,
    url: string,
}

export interface Species {
    name: string,
	classification: string,
	designation: string,
	average_height: number,
	skin_colors: string,
	hair_colors: string,
	eye_colors: string,
	average_lifespan: number,
	homeworld: string,
	language: string,
	people:string[],
	films: string[],
    created: string,
    edited: string,
    url: string,
}